name: AndroidBuild
on:
  pull_request:
    branches: [feat/refactor-structure]
  push:
    branches: [feat/refactor-structure]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: SoundNova.apk
          path: app/build/outputs/apk/app-debug.apk


